USE [master]
GO
/****** Object:  Database [TerrariumWhidbey]    Script Date: 05/14/2008 08:28:03 ******/
CREATE DATABASE [TerrariumWhidbey] ON  PRIMARY 
( NAME = N'TerrariumWhidbey_Data', FILENAME = N'C:\SQL\TerrariumWhidbey_Data.MDF' , SIZE = 120448KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'TerrariumWhidbey_Log', FILENAME = N'C:\SQL\TerrariumWhidbey_Log.LDF' , SIZE = 470144KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'TerrariumWhidbey', @new_cmptlevel=80
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TerrariumWhidbey].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [TerrariumWhidbey] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET ARITHABORT OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [TerrariumWhidbey] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TerrariumWhidbey] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TerrariumWhidbey] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET  ENABLE_BROKER 
GO
ALTER DATABASE [TerrariumWhidbey] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TerrariumWhidbey] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TerrariumWhidbey] SET  READ_WRITE 
GO
ALTER DATABASE [TerrariumWhidbey] SET RECOVERY FULL 
GO
ALTER DATABASE [TerrariumWhidbey] SET  MULTI_USER 
GO
ALTER DATABASE [TerrariumWhidbey] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [TerrariumWhidbey] SET DB_CHAINING OFF 